# -*- coding: utf-8 -*-
"""iris

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rG9OhJw8DGZ_0Qr5Q52RRU_LRnRHjJB7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

df=sns.load_dataset('iris')

print("dataset preview:")
print(df.head())
print("\ndataset shape:",df.shape)

print("=== BASIC INFORMATION===")
print("\ncolumn names and data types:")
print(df.info())
print("\nsummary statistics:")
print(df.describe())
print("\ncategorical column unique values:")
print("species:",df['species'].unique())



print("===missing values===")
missing=df.isnull().sum()
print("missing values per column;")
print(missing)

if missing.sum() == 0:
  print("great!no missing values found,")
else:
  plt.figure(figsize=(8,4))
  sns.heatmap(df.isnull(), cbar=false, cmap='viridis')
  plt.title('missing values heatmap')
  plt.show()

print("\n===DUPLICATES===")
print("duplicates before cleaning:",df.duplicated().sum())
if df.duplicated().sum()>0:
  print("\nduplicated row:")
  print(df[df.duplicated()])
  df=df.drop_duplicates()
  print("duplicated after cleaning:",df.duplicated().sum())

print("\n===UNIVARIATE ANALYSIS===")
num_cols =['sepal_length','sepal_width','petal_length','petal_width']
fig, axes=plt.subplots(2,2,figsize=(12, 8))
axes=axes.flatten()
for i,col in enumerate(num_cols):
  sns.histplot(data=df,x=col,kde=True,ax=axes[i],bins=20)
  axes[i].set_title(f'distribution of {col.replace("-"," ").title()}')
  axes[i].set_xlabel(col.replace("_"," ").title())
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
species_counts=df['species'].value_counts()
colors=['lightcoral','lightblue','lightgreen']
species_counts.plot(kind='bar',color=colors,edgecolor= 'black')
plt.title('Species distribution')
plt.xlabel('species')
plt.ylabel('count')
plt.xticks(rotation=0)
plt.show()

print("\nspecies distribution percentage:")
print(df['species'].value_counts(normalize=True).round(3)*100)

print("\n===BIVARIATE ANALYSIS===")
plt.figure(figsize=(10,6))
sns.scatterplot(data=df,x='sepal_length',y='sepal_width',
                hue='species',style='species',s=100,alpha=0.8)
plt.title('sepal length vs sepal width by species')
plt.xlabel('sepal length(cm)')
plt.ylabel('sepal width(cm)')
plt.legend(title='species')
plt.show()

fig,axes=plt.subplots(2,2,figsize=(14,10))
axes=axes.flatten()

for i,col in enumerate(num_cols):
    sns.boxplot(data=df, x='species', y=col, ax=axes[i], palette='Set2')
    axes[i].set_title(f'{col.replace("_"," ").title()}by species')
    axes[i].set_xlabel('Species')
    axes[i].set_ylabel(col.replace("_"," ").title())

plt.tight_layout()
plt.show()

print("\n===OUTLIER DETECTION===")
plt.figure(figsize=(12,6))
df[num_cols].boxplot()
plt.title('boxplot for outlier detection')
plt.ylabel('Measurement(cm)')
plt.xticks(rotation=45)
plt.show()
print("\n outlier analysis using IQR method:")
for col in num_cols:
  q1=df[col].quantile(0.25)
  q3=df[col].quantile(0.75)
  IQR=q3-q1
  lower_bound=q1-1.5*IQR
  upper_bound=q3+1.5*IQR

  outliers=df[(df[col]<lower_bound)|(df[col]>upper_bound)]
  print(f"{col:15s}:{len(outliers):2d} outliers"
       f"({len(outliers)/len(df)*100:.1f}%)")

  if len(outliers)>0:
    print(f"Outlier values:(outliers[col].values)")

print("\n===CORRELATION ANALYSIS===")
corr_matrix=df[num_cols].corr()
plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix,annot=True,cmap='coolwarm',center=0,fmt='.2f',square=True,linewidths=1)
plt.title('correlation heatmap of iris measurements')
plt.show()
print("\ncorrelation matrix:")
print(corr_matrix.round(3))

print("\n===PAIRWISE RELATIONSHIPS===")
pairplot = sns.pairplot(df, hue='species', palette='Set2',
                      diag_kind='kde',height=2.5)
pairplot.fig.suptitle('Pairwise Relationships in Iris Dataset',y=1.02)
plt.show()
sns.pairplot(df, hue='species',diag_kind='hist', palette='hls')
plt.suptitle('Pairwise Relationships with Histograms',y=1.02)
plt.show()

print("\n===CATEGORICAL INSIGHTS===")
print("\n1.species statistics:")
for species in df['species'].unique():
    print(f"\n---{species.upper()}---")
    species_data=df[df['species']==species]
    print(f"count:{len(species_data)}samples({len(species_data)/len(df)*100:.1f}%)")

    for col in num_cols:
        print(f"{col:15s}mean={species_data[col].mean():.2f}cm,"f"std={species_data[col].std():2f}cm")
print("\n2.statistical summary by species:")
summary_by_species=df.groupby('species')[num_cols].agg(['mean','std','min','max'])
print(summary_by_species.round(2))

fig,axes=plt.subplots(2,2,figsize=(14,10))
axes=axes.flatten()

for i,col in enumerate(num_cols):
    species_means=df.groupby('species')[col].mean()
    species_stds=df.groupby('species')[col].std()

    bars=axes[i].bar(species_means.index,species_means.values,color=['lightcoral','lightblue','lightgreen'],edgecolor='black',alpha=0.7)

    axes[i].errorbar(species_means.index,species_means.values,yerr=species_stds.values,fmt='none',color='black',capsize=5)

    axes[i].set_title(f'average{col.replace("_"," ").title()} by species')
    axes[i].set_ylabel(f'{col.replace("_"," ").title()}(cm)')

    for bar, mean_val in zip(bars, species_means.values):
       height=bar.get_height()
       axes[i].text(bar.get_x()+bar.get_width()/2.,height+0.02,f'{mean_val:.2f}',ha='center',va='bottom')
plt.tight_layout()
plt.show()