# -*- coding: utf-8 -*-
"""EDA DATA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIGkvg3dPGCDlJekYnL9_kT2Dv8pN2sE
"""

import pandas as pd
df=pd.read_csv("/content/Student - Sheet1.csv")
df.info()
df.describe()
df['marks'].hist()
df.plot.scatter(x='Study-hours',y='marks')
df.corr()
df.boxplot(column='marks')

from google.colab import drive
drive.mount('/content/drive')