# -*- coding: utf-8 -*-
"""EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q4SNAACTkIjjLzAgdBH7a-2AKcou7P2O
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df=sns.load_dataset('titanic')
df.head()

print("shape of data:",df.shape)
print("\ncolumn names:/n",df.columns)
print("\n data info:\n")
df.info()
print("\n summary statistics:\n")
print(df.describe(include='all'))

print(df.isnull().sum())
plt.figure(figsize=(10,5))
sns.heatmap (df.isnull(),cbar=False,cmap='viridis')
plt.title('Mssing values Heatmap')
plt.show()

print("Duplicate rows:",df.duplicated().sum())
df=df.drop_duplicates()

sns.histplot(df['age'],kde=True,color='skyblue')
plt.title('Age Distribution')
plt.show()
sns.countplot(x='sex',data=df,palette='pastel')
plt.title('Gender Distribution')
plt.show()
sns.countplot(x='class',data=df,palette='muted')
plt.title('Passenger Class Distribution')
plt.show()

sns.countplot(x='sex',hue='survived',data=df,palette='coolwarm')
plt.title('Survival by Gender')
plt.show()
sns.countplot(x='class',hue='survived',data=df,palette='coolwarm')
plt.title('Survival by Passenger Class')
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True),annot=True,cmap='YlGnBu')
plt.title('Correlation Heatmap')
plt.show()

sns.boxplot(x=df['fare'])
plt.title('Outlier Dectection in Fare')
plt.show()

sns.pairplot(df[['age','fare','pclass','survived']],hue='survived')
plt.show()

pd.crosstab(df['class'],df['sex'],margins=True)
df.groupby('class')['age'].mean()
df.groupby('class')['fare'].mean()