# -*- coding: utf-8 -*-
"""user data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibY0cmS79bgb4bWZ18BViRqLsWRDFfsA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")
df=pd.read_csv("/content/drive/MyDrive/User_Data.csv")
print("Dataset Preview")
print(df.head())

print("Missing values:")
missing_values=df.isnull().sum()
print(missing_values[missing_values > 0])
plt.figure(figsize=(8,4))
sns.heatmap(df.isnull(),cbar=False,cmap='viridis')
plt.title('Missing values Heatmap')
plt.show()

print("Number of duplicates before cleaning:",df.duplicated().sum())
df=df.drop_duplicates()
print("Number of duplicates after cleaning:",df.duplicated().sum())

numerical_cols=df.select_dtypes(include=[np.number]).columns

fig,axes=plt.subplots(1,len(numerical_cols),figsize=(15,4))
for idx,col in enumerate(numerical_cols):
  df[col].hist(ax=axes[idx],bins=30,edgecolor='black')
  axes[idx].set_title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

categorical_cols=df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    plt.figure(figsize=(8,4))
    df[col].value_counts().plot(kind='bar')
    plt.title(f'Distribution of{col}')
    plt.xticks(rotation=45)
    plt.show()

if'Gender' in df.columns and 'Age' in df.columns:
  plt.figure(figsize=(8,5))
  sns.boxplot(x='Gender',y='Age',data=df)
  plt.title('Age Distribution by Gender')
  plt.show()
  if len(numerical_cols) >=2:
    plt.figure(figsize=(8,5))
sns.scatterplot(x=numerical_cols[0],y=numerical_cols[1],data=df,alpha=0.6)
plt.title(f'{numerical_cols[0]} vs {numerical_cols[1]}')
plt.show()

correlation_matrix=df[numerical_cols].corr()
plt.figure(figsize=(8,6))
sns.heatmap(correlation_matrix,annot=True,cmap='coolwarm',center=0,fmt='.2f')
plt.title('correlation Heatmap')
plt.show()

plt.figure(figsize=(12,6))
df[numerical_cols].boxplot()
plt.title('Boxplot for Outlier Detection')
plt.xticks(rotation=45)
plt.show()
for col in numerical_cols:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)
  IQR=Q3-Q1
  lower_bound=Q1-1.5*IQR
  upper_bound=Q3+1.5*IQR
  outliers=df[(df[col]<upper_bound)]
  print(f"Outliers in {col}:{len(outliers)/len(df)*100:.2f}%")

if len(numerical_cols) <=5:
  sns.pairplot(df[numerical_cols])
  plt.suptitle('pairwise Relationship',y=1.02)
  plt.show()
else:
  print(f"Too many columns({len(numerical_cols)}for pairplot.try subset.")

for col in categorical_cols:
  print(f"\n==={col}===")
  print("Values Counts:")
  print(df[col].value_counts())
  print("\nPercentage Distribution:")
  print(df[col].value_counts(normalize=True).round(3)*100)
  if len(numerical_cols) >0:
    print(f"\nSatistics by{col}:")
    for num_col in numerical_cols:
      print(f"\n{num_col}by{col}:")
      print(df.groupby(col)[num_col].describe())